M48
; DRILL file {KiCad 8.0.3} date 2024-09-22T17:39:38+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-22T17:39:38+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.000
%
G90
G05
T2
X-9.25Y-20.0
X9.25Y-20.0
T3
X0.0Y-20.0
T1
G00X-5.5Y-20.0
M15
G01X-5.08Y-20.0
M16
G05
G00X5.08Y-20.0
M15
G01X5.5Y-20.0
M16
G05
M30
